theme: jekyll-theme-minimal
title: Miguel Moço
description: A portfolio of TEI and EPUB editions creted through my learning process. This is fruit of my insterest in cultural heritage preservation and pratices that ensure accessibility for people of various disabilities.
